matcher:
  KDTreeMatcher:
    knn: 3
    maxDist: 2.0
    epsilon: 1

outlierFilters:
#   - TrimmedDistOutlierFilter:
#       ratio: 0.8

errorMinimizer:
  PointToPlaneErrorMinimizer:
    force4DOF: 1

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 2
  - CounterTransformationChecker:
      maxIterationCount: 40
  - BoundTransformationChecker:
      maxRotationNorm: 5000.0
      maxTranslationNorm: 5000.0

inspector: NullInspector

logger: NullLogger
